# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: splitlearning.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'splitlearning.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13splitlearning.proto\x12\rsplitlearning\"\x07\n\x05\x45mpty\"d\n\x0e\x43lientToServer\x12\x0e\n\x06values\x18\x01 \x03(\x02\x12\x12\n\nbatch_size\x18\x02 \x01(\x05\x12\x11\n\tclient_id\x18\x03 \x01(\x05\x12\x0c\n\x04step\x18\x04 \x01(\x03\x12\r\n\x05token\x18\x05 \x01(\t\"Q\n\x0eServerToClient\x12\x0e\n\x06values\x18\x01 \x03(\x02\x12\x12\n\nbatch_size\x18\x02 \x01(\x05\x12\x0c\n\x04step\x18\x03 \x01(\x03\x12\r\n\x05token\x18\x04 \x01(\t\"Z\n\x04Info\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\x12\x0f\n\x07updates\x18\x02 \x01(\x03\x12\x0b\n\x03pid\x18\x03 \x01(\x05\x12\x0e\n\x06\x64\x65vice\x18\x04 \x01(\t\x12\x0f\n\x07\x63lients\x18\x05 \x01(\x05\x32\x9c\x03\n\rSplitLearning\x12\x34\n\x07GetInfo\x12\x14.splitlearning.Empty\x1a\x13.splitlearning.Info\x12G\n\x07\x46orward\x12\x1d.splitlearning.ClientToServer\x1a\x1d.splitlearning.ServerToClient\x12H\n\x08\x42\x61\x63kward\x12\x1d.splitlearning.ClientToServer\x1a\x1d.splitlearning.ServerToClient\x12H\n\x08\x45valuate\x12\x1d.splitlearning.ClientToServer\x1a\x1d.splitlearning.ServerToClient\x12;\n\x0eSaveCheckpoint\x12\x14.splitlearning.Empty\x1a\x13.splitlearning.Info\x12;\n\x0eLoadCheckpoint\x12\x14.splitlearning.Empty\x1a\x13.splitlearning.Infob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'splitlearning_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=38
  _globals['_EMPTY']._serialized_end=45
  _globals['_CLIENTTOSERVER']._serialized_start=47
  _globals['_CLIENTTOSERVER']._serialized_end=147
  _globals['_SERVERTOCLIENT']._serialized_start=149
  _globals['_SERVERTOCLIENT']._serialized_end=230
  _globals['_INFO']._serialized_start=232
  _globals['_INFO']._serialized_end=322
  _globals['_SPLITLEARNING']._serialized_start=325
  _globals['_SPLITLEARNING']._serialized_end=737
# @@protoc_insertion_point(module_scope)
