# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import splitlearning_pb2 as splitlearning__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in splitlearning_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SplitLearningStub(object):
    """U-Shaped: este contrato NÃO possui campos de imagens, rótulos ou loss.
    Dois RPCs completam um lote: forward de M2 e backward de M2.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInfo = channel.unary_unary(
                '/splitlearning.SplitLearning/GetInfo',
                request_serializer=splitlearning__pb2.Empty.SerializeToString,
                response_deserializer=splitlearning__pb2.Info.FromString,
                _registered_method=True)
        self.Forward = channel.unary_unary(
                '/splitlearning.SplitLearning/Forward',
                request_serializer=splitlearning__pb2.ClientToServer.SerializeToString,
                response_deserializer=splitlearning__pb2.ServerToClient.FromString,
                _registered_method=True)
        self.Backward = channel.unary_unary(
                '/splitlearning.SplitLearning/Backward',
                request_serializer=splitlearning__pb2.ClientToServer.SerializeToString,
                response_deserializer=splitlearning__pb2.ServerToClient.FromString,
                _registered_method=True)
        self.Evaluate = channel.unary_unary(
                '/splitlearning.SplitLearning/Evaluate',
                request_serializer=splitlearning__pb2.ClientToServer.SerializeToString,
                response_deserializer=splitlearning__pb2.ServerToClient.FromString,
                _registered_method=True)
        self.SaveCheckpoint = channel.unary_unary(
                '/splitlearning.SplitLearning/SaveCheckpoint',
                request_serializer=splitlearning__pb2.Empty.SerializeToString,
                response_deserializer=splitlearning__pb2.Info.FromString,
                _registered_method=True)
        self.LoadCheckpoint = channel.unary_unary(
                '/splitlearning.SplitLearning/LoadCheckpoint',
                request_serializer=splitlearning__pb2.Empty.SerializeToString,
                response_deserializer=splitlearning__pb2.Info.FromString,
                _registered_method=True)


class SplitLearningServicer(object):
    """U-Shaped: este contrato NÃO possui campos de imagens, rótulos ou loss.
    Dois RPCs completam um lote: forward de M2 e backward de M2.
    """

    def GetInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Forward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Backward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Evaluate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveCheckpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadCheckpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SplitLearningServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInfo,
                    request_deserializer=splitlearning__pb2.Empty.FromString,
                    response_serializer=splitlearning__pb2.Info.SerializeToString,
            ),
            'Forward': grpc.unary_unary_rpc_method_handler(
                    servicer.Forward,
                    request_deserializer=splitlearning__pb2.ClientToServer.FromString,
                    response_serializer=splitlearning__pb2.ServerToClient.SerializeToString,
            ),
            'Backward': grpc.unary_unary_rpc_method_handler(
                    servicer.Backward,
                    request_deserializer=splitlearning__pb2.ClientToServer.FromString,
                    response_serializer=splitlearning__pb2.ServerToClient.SerializeToString,
            ),
            'Evaluate': grpc.unary_unary_rpc_method_handler(
                    servicer.Evaluate,
                    request_deserializer=splitlearning__pb2.ClientToServer.FromString,
                    response_serializer=splitlearning__pb2.ServerToClient.SerializeToString,
            ),
            'SaveCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveCheckpoint,
                    request_deserializer=splitlearning__pb2.Empty.FromString,
                    response_serializer=splitlearning__pb2.Info.SerializeToString,
            ),
            'LoadCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadCheckpoint,
                    request_deserializer=splitlearning__pb2.Empty.FromString,
                    response_serializer=splitlearning__pb2.Info.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'splitlearning.SplitLearning', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('splitlearning.SplitLearning', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SplitLearning(object):
    """U-Shaped: este contrato NÃO possui campos de imagens, rótulos ou loss.
    Dois RPCs completam um lote: forward de M2 e backward de M2.
    """

    @staticmethod
    def GetInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/splitlearning.SplitLearning/GetInfo',
            splitlearning__pb2.Empty.SerializeToString,
            splitlearning__pb2.Info.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Forward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/splitlearning.SplitLearning/Forward',
            splitlearning__pb2.ClientToServer.SerializeToString,
            splitlearning__pb2.ServerToClient.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Backward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/splitlearning.SplitLearning/Backward',
            splitlearning__pb2.ClientToServer.SerializeToString,
            splitlearning__pb2.ServerToClient.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Evaluate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/splitlearning.SplitLearning/Evaluate',
            splitlearning__pb2.ClientToServer.SerializeToString,
            splitlearning__pb2.ServerToClient.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/splitlearning.SplitLearning/SaveCheckpoint',
            splitlearning__pb2.Empty.SerializeToString,
            splitlearning__pb2.Info.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/splitlearning.SplitLearning/LoadCheckpoint',
            splitlearning__pb2.Empty.SerializeToString,
            splitlearning__pb2.Info.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
