# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ml.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ml.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08ml.proto\x12\x05mlrpc\"%\n\x06Sample\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x02\x12\r\n\x05label\x18\x02 \x01(\x05\",\n\nFitRequest\x12\x1e\n\x07samples\x18\x01 \x03(\x0b\x32\r.mlrpc.Sample\"\x1a\n\x0b\x46itResponse\x12\x0b\n\x03\x61\x63\x63\x18\x01 \x01(\x02\"0\n\x0ePredictRequest\x12\x1e\n\x07samples\x18\x01 \x03(\x0b\x32\r.mlrpc.Sample\"3\n\x0fPredictResponse\x12\x13\n\x0bpredictions\x18\x01 \x03(\x05\x12\x0b\n\x03\x61\x63\x63\x18\x02 \x01(\x02\x32v\n\x02ML\x12\x31\n\x06GetFit\x12\x11.mlrpc.FitRequest\x1a\x12.mlrpc.FitResponse\"\x00\x12=\n\nGetPredict\x12\x15.mlrpc.PredictRequest\x1a\x16.mlrpc.PredictResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SAMPLE']._serialized_start=19
  _globals['_SAMPLE']._serialized_end=56
  _globals['_FITREQUEST']._serialized_start=58
  _globals['_FITREQUEST']._serialized_end=102
  _globals['_FITRESPONSE']._serialized_start=104
  _globals['_FITRESPONSE']._serialized_end=130
  _globals['_PREDICTREQUEST']._serialized_start=132
  _globals['_PREDICTREQUEST']._serialized_end=180
  _globals['_PREDICTRESPONSE']._serialized_start=182
  _globals['_PREDICTRESPONSE']._serialized_end=233
  _globals['_ML']._serialized_start=235
  _globals['_ML']._serialized_end=353
# @@protoc_insertion_point(module_scope)
