syntax = "proto3";

package mlrpc;

message Sample {
    repeated float data = 1;
    int32 label = 2;
}

message FitRequest {
    repeated Sample samples = 1;
}

message TrainingDataRequest {
    int32 client_id = 1;
}

message TrainingDataResponse {
    repeated Sample samples = 1;
}

message ModelUpdateRequest {
    int32 client_id = 1;
    repeated float weights = 2;
    repeated float intercept = 3;
}

message ModelUpdateResponse {
    bool accepted = 1;
    float global_acc = 2;
    float global_acc_without_detection = 3;
}

message FitResponse {
    float acc = 1;
}

message PredictRequest {
    repeated Sample samples = 1;
}

message PredictResponse {
    repeated int32 predictions = 1;
    float acc = 2;
}

service ML {
    rpc GetTrainingData(TrainingDataRequest) returns (TrainingDataResponse) {}
    rpc SubmitModelUpdate(ModelUpdateRequest) returns (ModelUpdateResponse) {}
    rpc GetFit(FitRequest) returns (FitResponse) {}
    rpc GetPredict(PredictRequest) returns (PredictResponse) {}
}
