# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ml_pb2 as ml__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ml_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MLStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTrainingData = channel.unary_unary(
                '/mlrpc.ML/GetTrainingData',
                request_serializer=ml__pb2.TrainingDataRequest.SerializeToString,
                response_deserializer=ml__pb2.TrainingDataResponse.FromString,
                _registered_method=True)
        self.SubmitModelUpdate = channel.unary_unary(
                '/mlrpc.ML/SubmitModelUpdate',
                request_serializer=ml__pb2.ModelUpdateRequest.SerializeToString,
                response_deserializer=ml__pb2.ModelUpdateResponse.FromString,
                _registered_method=True)
        self.GetFit = channel.unary_unary(
                '/mlrpc.ML/GetFit',
                request_serializer=ml__pb2.FitRequest.SerializeToString,
                response_deserializer=ml__pb2.FitResponse.FromString,
                _registered_method=True)
        self.GetPredict = channel.unary_unary(
                '/mlrpc.ML/GetPredict',
                request_serializer=ml__pb2.PredictRequest.SerializeToString,
                response_deserializer=ml__pb2.PredictResponse.FromString,
                _registered_method=True)


class MLServicer:
    """Missing associated documentation comment in .proto file."""

    def GetTrainingData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitModelUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPredict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MLServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTrainingData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrainingData,
                    request_deserializer=ml__pb2.TrainingDataRequest.FromString,
                    response_serializer=ml__pb2.TrainingDataResponse.SerializeToString,
            ),
            'SubmitModelUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitModelUpdate,
                    request_deserializer=ml__pb2.ModelUpdateRequest.FromString,
                    response_serializer=ml__pb2.ModelUpdateResponse.SerializeToString,
            ),
            'GetFit': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFit,
                    request_deserializer=ml__pb2.FitRequest.FromString,
                    response_serializer=ml__pb2.FitResponse.SerializeToString,
            ),
            'GetPredict': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPredict,
                    request_deserializer=ml__pb2.PredictRequest.FromString,
                    response_serializer=ml__pb2.PredictResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mlrpc.ML', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mlrpc.ML', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ML:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTrainingData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlrpc.ML/GetTrainingData',
            ml__pb2.TrainingDataRequest.SerializeToString,
            ml__pb2.TrainingDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitModelUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlrpc.ML/SubmitModelUpdate',
            ml__pb2.ModelUpdateRequest.SerializeToString,
            ml__pb2.ModelUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlrpc.ML/GetFit',
            ml__pb2.FitRequest.SerializeToString,
            ml__pb2.FitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPredict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlrpc.ML/GetPredict',
            ml__pb2.PredictRequest.SerializeToString,
            ml__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
