# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ml.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'ml.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08ml.proto\x12\x04lab4\"\x07\n\x05Vazio\"O\n\x04Info\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x10\n\x08\x64imensao\x18\x02 \x01(\x05\x12\x0e\n\x06limiar\x18\x03 \x01(\x01\x12\x13\n\x0binstance_id\x18\x04 \x01(\t\"T\n\x0cVetorRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0e\n\x06rodada\x18\x02 \x01(\t\x12\x10\n\x08model_id\x18\x03 \x01(\t\x12\x0f\n\x07valores\x18\x04 \x03(\x02\"c\n\tResultado\x12\x0e\n\x06rodada\x18\x01 \x01(\t\x12\x11\n\tdistancia\x18\x02 \x01(\x01\x12\x11\n\tsimilares\x18\x03 \x01(\x08\x12\x0e\n\x06limiar\x18\x04 \x01(\x01\x12\x10\n\x08\x63lientes\x18\x05 \x03(\t2f\n\x0cSimilaridade\x12\"\n\x07GetInfo\x12\x0b.lab4.Vazio\x1a\n.lab4.Info\x12\x32\n\x0b\x45nviarVetor\x12\x12.lab4.VetorRequest\x1a\x0f.lab4.Resultadob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VAZIO']._serialized_start=18
  _globals['_VAZIO']._serialized_end=25
  _globals['_INFO']._serialized_start=27
  _globals['_INFO']._serialized_end=106
  _globals['_VETORREQUEST']._serialized_start=108
  _globals['_VETORREQUEST']._serialized_end=192
  _globals['_RESULTADO']._serialized_start=194
  _globals['_RESULTADO']._serialized_end=293
  _globals['_SIMILARIDADE']._serialized_start=295
  _globals['_SIMILARIDADE']._serialized_end=397
# @@protoc_insertion_point(module_scope)
